# Python CircleCI 2.0 configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch # Use the same Docker base as the project

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .course4
            . .course4/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths: [./.course4]

      - run:
          name: run lint
          command: |
            . .course4/bin/activate
            make lint
workflows:
  project4workflow:
    jobs:
      - build